name: weather
description: "The weather app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.2"
  flutter: ">=3.27.4"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  basic_utils: ^5.7.0
  chopper: ^8.1.0
  crypto: ^3.0.6
  equatable: ^2.0.7
  event_bus: ^2.0.1
  flutter_bloc: ^9.0.0
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.3
  rxdart: ^0.28.0
  sliver_tools: ^0.2.12
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_resolvers: 2.4.3
  build_runner: 2.4.14
  chopper_generator: ^8.1.0
  freezed: ^2.5.8
  injectable_generator: ^2.7.0
  intl_utils: ^2.8.10

flutter:
  uses-material-design: true